"""Init SQLModel schema

Revision ID: 8a53c3d8e0e0
Revises:
Create Date: 2025-07-29 11:58:59.961494

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a53c3d8e0e0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compact_memories",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("task_ids", sa.JSON(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key_points", sa.JSON(), nullable=True),
        sa.Column("entities", sa.JSON(), nullable=True),
        sa.Column("semantic_labels", sa.JSON(), nullable=True),
        sa.Column("turn_count", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("compressed_token_count", sa.Integer(), nullable=True),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_compact_memories_time_range",
        "compact_memories",
        ["start_time", "end_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compact_memories_end_time"), "compact_memories", ["end_time"], unique=False
    )
    op.create_index(
        op.f("ix_compact_memories_processed"), "compact_memories", ["processed"], unique=False
    )
    op.create_index(
        op.f("ix_compact_memories_start_time"), "compact_memories", ["start_time"], unique=False
    )
    op.create_table(
        "conversation_turns",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("source_entity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_entity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("conversation_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_query", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_response", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("llm_context", sa.JSON(), nullable=True),
        sa.Column("tools_used", sa.Boolean(), nullable=False),
        sa.Column("trace_id", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("total_duration_ms", sa.Float(), nullable=True),
        sa.Column("llm_duration_ms", sa.Float(), nullable=True),
        sa.Column("tools_duration_ms", sa.Float(), nullable=True),
        sa.Column("user_metadata", sa.JSON(), nullable=True),
        sa.Column("agent_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "COMPLETED", "ERROR", "PARTIAL", "ABANDONED", name="turnstatus"),
            nullable=False,
        ),
        sa.Column("error_details", sa.JSON(), nullable=True),
        sa.Column("compacted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_turns_agent_number", "conversation_turns", ["agent_id", "turn_number"], unique=False
    )
    op.create_index(
        "idx_turns_agent_time", "conversation_turns", ["agent_id", "timestamp"], unique=False
    )
    op.create_index(
        "idx_turns_agent_turn_unique",
        "conversation_turns",
        ["agent_id", "turn_number"],
        unique=True,
    )
    op.create_index("idx_turns_compacted", "conversation_turns", ["compacted"], unique=False)
    op.create_index(
        "idx_turns_conversation_type", "conversation_turns", ["conversation_type"], unique=False
    )
    op.create_index(
        "idx_turns_source_entity", "conversation_turns", ["source_entity"], unique=False
    )
    op.create_index(
        "idx_turns_target_entity", "conversation_turns", ["target_entity"], unique=False
    )
    op.create_index(
        op.f("ix_conversation_turns_agent_id"), "conversation_turns", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_conversation_turns_task_id"), "conversation_turns", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_conversation_turns_timestamp"), "conversation_turns", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_conversation_turns_trace_id"), "conversation_turns", ["trace_id"], unique=False
    )
    op.create_table(
        "long_term_memories",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_long_term_memories_created_at", "long_term_memories", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_long_term_memories_task_id"), "long_term_memories", ["task_id"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column("task_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("assigned_agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("agent_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("outputs", sa.JSON(), nullable=True),
        sa.Column("progress_percentage", sa.Integer(), nullable=False),
        sa.Column("progress_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("milestones", sa.JSON(), nullable=True),
        sa.Column("execution_time_ms", sa.Float(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("tool_calls_count", sa.Integer(), nullable=True),
        sa.Column("parent_task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["parent_task_id"], ["tasks.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tasks_assigned_agent", "tasks", ["assigned_agent_id", "status"], unique=False
    )
    op.create_index("idx_tasks_status_priority", "tasks", ["status", "priority"], unique=False)
    op.create_index("idx_tasks_type_status", "tasks", ["task_type", "status"], unique=False)
    op.create_index(
        op.f("ix_tasks_assigned_agent_id"), "tasks", ["assigned_agent_id"], unique=False
    )
    op.create_index(op.f("ix_tasks_parent_task_id"), "tasks", ["parent_task_id"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_index(op.f("ix_tasks_task_type"), "tasks", ["task_type"], unique=False)
    op.create_table(
        "telemetry_spans",
        sa.Column("span_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_span_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("service_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=True),
        sa.Column("events", sa.JSON(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("span_id"),
    )
    op.create_index("idx_telemetry_name", "telemetry_spans", ["name"], unique=False)
    op.create_index("idx_telemetry_start_time", "telemetry_spans", ["start_time"], unique=False)
    op.create_index("idx_telemetry_trace_id", "telemetry_spans", ["trace_id"], unique=False)
    op.create_index(op.f("ix_telemetry_spans_name"), "telemetry_spans", ["name"], unique=False)
    op.create_index(
        op.f("ix_telemetry_spans_start_time"), "telemetry_spans", ["start_time"], unique=False
    )
    op.create_index(
        op.f("ix_telemetry_spans_trace_id"), "telemetry_spans", ["trace_id"], unique=False
    )
    op.create_table(
        "task_execution_requests",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requested_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("request_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("execution_context", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_execution_requests_created", "task_execution_requests", ["created_at"], unique=False
    )
    op.create_index(
        "idx_execution_requests_task_status",
        "task_execution_requests",
        ["task_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_execution_requests_status"),
        "task_execution_requests",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_execution_requests_task_id"),
        "task_execution_requests",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "task_parameters",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("parameter_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("default_value", sa.JSON(), nullable=True),
        sa.Column("validation_rules", sa.JSON(), nullable=True),
        sa.Column("allowed_values", sa.JSON(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("ui_hints", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_task_parameters_task_order",
        "task_parameters",
        ["task_id", "display_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_parameters_task_id"), "task_parameters", ["task_id"], unique=False
    )
    op.create_table(
        "tool_usage",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("turn_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tool_args", sa.JSON(), nullable=True),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("user_decision", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("decision_timestamp", sa.DateTime(), nullable=True),
        sa.Column("execution_started_at", sa.DateTime(), nullable=True),
        sa.Column("execution_completed_at", sa.DateTime(), nullable=True),
        sa.Column("execution_status", sa.String(), nullable=True),
        sa.Column("execution_result", sa.JSON(), nullable=True),
        sa.Column("execution_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("trace_id", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.ForeignKeyConstraint(["turn_id"], ["conversation_turns.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_tool_usage_created", "tool_usage", ["created_at"], unique=False)
    op.create_index(op.f("ix_tool_usage_entity_id"), "tool_usage", ["entity_id"], unique=False)
    op.create_index(
        op.f("ix_tool_usage_execution_status"), "tool_usage", ["execution_status"], unique=False
    )
    op.create_index(op.f("ix_tool_usage_tool_name"), "tool_usage", ["tool_name"], unique=False)
    op.create_index(op.f("ix_tool_usage_turn_id"), "tool_usage", ["turn_id"], unique=False)
    op.create_index(
        op.f("ix_tool_usage_user_decision"), "tool_usage", ["user_decision"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tool_usage_user_decision"), table_name="tool_usage")
    op.drop_index(op.f("ix_tool_usage_turn_id"), table_name="tool_usage")
    op.drop_index(op.f("ix_tool_usage_tool_name"), table_name="tool_usage")
    op.drop_index(op.f("ix_tool_usage_execution_status"), table_name="tool_usage")
    op.drop_index(op.f("ix_tool_usage_entity_id"), table_name="tool_usage")
    op.drop_index("idx_tool_usage_created", table_name="tool_usage")
    op.drop_table("tool_usage")
    op.drop_index(op.f("ix_task_parameters_task_id"), table_name="task_parameters")
    op.drop_index("idx_task_parameters_task_order", table_name="task_parameters")
    op.drop_table("task_parameters")
    op.drop_index(op.f("ix_task_execution_requests_task_id"), table_name="task_execution_requests")
    op.drop_index(op.f("ix_task_execution_requests_status"), table_name="task_execution_requests")
    op.drop_index("idx_execution_requests_task_status", table_name="task_execution_requests")
    op.drop_index("idx_execution_requests_created", table_name="task_execution_requests")
    op.drop_table("task_execution_requests")
    op.drop_index(op.f("ix_telemetry_spans_trace_id"), table_name="telemetry_spans")
    op.drop_index(op.f("ix_telemetry_spans_start_time"), table_name="telemetry_spans")
    op.drop_index(op.f("ix_telemetry_spans_name"), table_name="telemetry_spans")
    op.drop_index("idx_telemetry_trace_id", table_name="telemetry_spans")
    op.drop_index("idx_telemetry_start_time", table_name="telemetry_spans")
    op.drop_index("idx_telemetry_name", table_name="telemetry_spans")
    op.drop_table("telemetry_spans")
    op.drop_index(op.f("ix_tasks_task_type"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_parent_task_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_assigned_agent_id"), table_name="tasks")
    op.drop_index("idx_tasks_type_status", table_name="tasks")
    op.drop_index("idx_tasks_status_priority", table_name="tasks")
    op.drop_index("idx_tasks_assigned_agent", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_long_term_memories_task_id"), table_name="long_term_memories")
    op.drop_index("idx_long_term_memories_created_at", table_name="long_term_memories")
    op.drop_table("long_term_memories")
    op.drop_index(op.f("ix_conversation_turns_trace_id"), table_name="conversation_turns")
    op.drop_index(op.f("ix_conversation_turns_timestamp"), table_name="conversation_turns")
    op.drop_index(op.f("ix_conversation_turns_task_id"), table_name="conversation_turns")
    op.drop_index(op.f("ix_conversation_turns_agent_id"), table_name="conversation_turns")
    op.drop_index("idx_turns_target_entity", table_name="conversation_turns")
    op.drop_index("idx_turns_source_entity", table_name="conversation_turns")
    op.drop_index("idx_turns_conversation_type", table_name="conversation_turns")
    op.drop_index("idx_turns_compacted", table_name="conversation_turns")
    op.drop_index("idx_turns_agent_turn_unique", table_name="conversation_turns")
    op.drop_index("idx_turns_agent_time", table_name="conversation_turns")
    op.drop_index("idx_turns_agent_number", table_name="conversation_turns")
    op.drop_table("conversation_turns")
    op.drop_index(op.f("ix_compact_memories_start_time"), table_name="compact_memories")
    op.drop_index(op.f("ix_compact_memories_processed"), table_name="compact_memories")
    op.drop_index(op.f("ix_compact_memories_end_time"), table_name="compact_memories")
    op.drop_index("idx_compact_memories_time_range", table_name="compact_memories")
    op.drop_table("compact_memories")
    # ### end Alembic commands ###
