name: Ambient
options:
  bundleIdPrefix: com.crestviewlabs
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  
settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
  DEVELOPMENT_TEAM: ""
  
targets:
  Ambient:
    type: application
    platform: macOS
    sources:
      - path: Ambient
        createIntermediateGroups: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.crestviewlabs.ambient
      PRODUCT_NAME: Ambient
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_HARDENED_RUNTIME: YES
      CODE_SIGN_STYLE: Automatic
      COMBINE_HIDPI_IMAGES: YES
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "14.0"
      INFOPLIST_FILE: Ambient/Info.plist
    dependencies:
      - package: MetagenAPI
        product: MetagenAPI
        
packages:
  MetagenAPI:
    path: ../api/swift