"""Add foreign key constraint to tool_usage.turn_id

Revision ID: 0ca1334ac434
Revises: 93e6f3fdea9c
Create Date: 2025-07-19 22:38:22.394527

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ca1334ac434"
down_revision: Union[str, Sequence[str], None] = "93e6f3fdea9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add foreign key constraint from tool_usage.turn_id to conversation_turns.id
    # SQLite requires batch mode for adding constraints
    with op.batch_alter_table("tool_usage", recreate="always") as batch_op:
        batch_op.create_foreign_key(
            "fk_tool_usage_turn_id", "conversation_turns", ["turn_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove foreign key constraint
    # SQLite requires batch mode for dropping constraints
    with op.batch_alter_table("tool_usage", recreate="always") as batch_op:
        batch_op.drop_constraint("fk_tool_usage_turn_id", type_="foreignkey")
    # ### end Alembic commands ###
