"""Replace session_id with agent_id in conversation_turns

Revision ID: a33fa66e6935
Revises: 9437fde74565
Create Date: 2025-07-04 18:24:47.020384

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a33fa66e6935"
down_revision: Union[str, Sequence[str], None] = "9437fde74565"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversation_turns", sa.Column("agent_id", sa.String(), nullable=False))
    op.drop_index(op.f("idx_turns_session_number"), table_name="conversation_turns")
    op.drop_index(op.f("idx_turns_session_time"), table_name="conversation_turns")
    op.drop_index(op.f("idx_turns_session_turn_unique"), table_name="conversation_turns")
    op.create_index("idx_turns_agent_id", "conversation_turns", ["agent_id"], unique=False)
    op.create_index(
        "idx_turns_agent_number", "conversation_turns", ["agent_id", "turn_number"], unique=False
    )
    op.create_index(
        "idx_turns_agent_time", "conversation_turns", ["agent_id", "timestamp"], unique=False
    )
    op.create_index(
        "idx_turns_agent_turn_unique",
        "conversation_turns",
        ["agent_id", "turn_number"],
        unique=True,
    )
    op.drop_column("conversation_turns", "session_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversation_turns", sa.Column("session_id", sa.VARCHAR(), nullable=False))
    op.drop_index("idx_turns_agent_turn_unique", table_name="conversation_turns")
    op.drop_index("idx_turns_agent_time", table_name="conversation_turns")
    op.drop_index("idx_turns_agent_number", table_name="conversation_turns")
    op.drop_index("idx_turns_agent_id", table_name="conversation_turns")
    op.create_index(
        op.f("idx_turns_session_turn_unique"),
        "conversation_turns",
        ["session_id", "turn_number"],
        unique=True,
    )
    op.create_index(
        op.f("idx_turns_session_time"),
        "conversation_turns",
        ["session_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("idx_turns_session_number"),
        "conversation_turns",
        ["session_id", "turn_number"],
        unique=False,
    )
    op.drop_column("conversation_turns", "agent_id")
    # ### end Alembic commands ###
